import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
// import { signOut, useSession } from "next-auth/react";
import { useEffect, useState } from "react";

const Nav = () => {
  const [userName, setUserName] = useState<string>("User");
  const [isLoggedIn, setIsLoggedIn] = useState<boolean>(false);
  const [role, setRole] = useState<string>("User");

  useEffect(() => {
    // Check if the user is logged in by checking localStorage for the token
    const token = localStorage.getItem("token");
    const storedUserName = localStorage.getItem("userName");
    const storedRole = localStorage.getItem("role");

    if (token && storedUserName && storedRole) {
      setIsLoggedIn(true);
      setUserName(storedUserName); // Set the user's name from localStorage
      setRole(storedRole); // Set the user's role from localStorage
    }
  }, []); // Empty dependency array so this runs only once on mount

  const handleLogout = () => {
    // Clear localStorage and update state on logout
    localStorage.removeItem("token");
    localStorage.removeItem("userName");
    setIsLoggedIn(false);
    setUserName("");
  };
  const router = useRouter();

  const handleSignIn = () => {
    router.push("/user/login");
  };

  return (
    <>
      <Head>
        <title>Course selling application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="p-4 mb-6 flex items-center space-x-3">
        <ul className="flex gap-2">
          <li>
            <Link href="/" className="underline">
              <span className="inline-block ml-3 text-3xl font-bold truncate text-blue-700">
                coursera
              </span>
            </Link>
          </li>
        </ul>
        <div className="text-right text-sm flex-1">
          {isLoggedIn
            ? (
              <div className="text-slate-700">
                {role === "ADMIN" && (
                  <Link href="/admin/dashboard" className="underline">
                    Admin portal
                  </Link>
                )}
                <Link href="/" className="underline p-4 font-bold">Home</Link>
                <span className="border border-black rounded font-medium m-2 p-2">
                  Hello, {userName}
                </span>
                <button
                  className="bg-black hover:bg-gray-900 text-white font-medium font-sans py-2 px-4 rounded"
                  onClick={handleLogout}
                >
                  Sign out
                </button>
              </div>
            )
            : (
              <p>
                <button
                  className="bg-blue-700 hover:bg-blue-900 text-white font-medium font-sans py-2 px-4 rounded"
                  onClick={handleSignIn}
                >
                  Login
                </button>
              </p>
            )}
        </div>
      </nav>
    </>
  );
};

export default Nav;
