import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import { useRouter } from "next/router"
import { useSession, signIn, signOut } from "next-auth/react"

const Nav = () => {
  const { data: session } = useSession()
  const router = useRouter()
  const handleSignIn = () => {
    router.push("/user/login")
  }
  return (
    <>
      <Head>
        <title>Course selling application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='p-4 mb-6 flex items-center space-x-3'>
        <ul className='flex gap-2'>
          <li>
            <Link href="/" className='underline'>
            <span className="inline-block ml-3 text-3xl font-bold truncate text-blue-700">
              coursera
            </span>
            </Link>
          </li>
          {session && (
            <li>
              <Link href="/admin" className='underline'>
                Admin
              </Link>
            </li>
          )}
        </ul>
        <div className='text-right text-sm flex-1'>
          {session ? (
            <div className='text-slate-700'>
              Signed in as {session.user?.email} <br />
              <button className='underline' onClick={() => signOut()}>Sign out</button>
            </div>
          ) : (
            <p>
              <button className='bg-blue-700 hover:bg-blue-900 text-white font-medium font-sans py-2 px-4 rounded' onClick={() => handleSignIn()}>
                Login
              </button>
            </p>
          )}
        </div>
      </nav>
    </>
  )
}

export default Nav;
