import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import { useSession, signIn, signOut } from "next-auth/react"

const Nav = () => {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Coursera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className='p-4 mb-6 flex items-center space-x-3'>
        <div className='text-right text-sm'>
          {session ? (
            <div className='text-slate-700'>
              Signed in as {session.user?.email} <br />
              <button className='underline' onClick={() => signOut()}>Sign out</button>
            </div>
          ) : (
            <p>
              <button onClick={() => signIn()}>Sign in</button>
            </p>
          )}
        </div>
      </nav>
    </>
  )
}

export default Nav;
